---
## 🔹 FASE 1 — Limpeza e Padronização

### 1. Consolidação e Tipagem

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv('Housing.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.0,2,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(15)
memory usage: 3.5 MB

In [6]:
cols = ['sqft_living','sqft_lot', 'sqft_above' ,'sqft_basement' , 'sqft_living15' , 'sqft_lot15']

for col in cols:
    df[col] = df[col] / 10.76389999

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  float64
 6   sqft_lot       21613 non-null  float64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  float64
 13  sqft_basement  21613 non-null  float64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  float64
 20  sqft_lot15     21613 non-null  float64
dtypes: datetime64[us](1), float64(11), int64(9)
memory usage: 3.5 MB

### 2 Tratamento de Valores Ausentes

In [8]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [9]:
df['date'].unique()

<DatetimeArray>
['2014-10-13 00:00:00', '2014-12-09 00:00:00', '2015-02-25 00:00:00',
 '2015-02-18 00:00:00', '2014-05-12 00:00:00', '2014-06-27 00:00:00',
 '2015-01-15 00:00:00', '2015-04-15 00:00:00', '2015-03-12 00:00:00',
 '2015-04-03 00:00:00',
 ...
 '2015-03-08 00:00:00', '2014-08-30 00:00:00', '2015-05-27 00:00:00',
 '2015-03-22 00:00:00', '2015-02-15 00:00:00', '2014-10-11 00:00:00',
 '2015-02-01 00:00:00', '2014-11-30 00:00:00', '2014-08-24 00:00:00',
 '2014-07-27 00:00:00']
Length: 372, dtype: datetime64[us]

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,21613,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580306e+09,2014-10-29 04:38:01.959931,5.400886e+05,3.370795,2.114757,193.229196,1403.484572,1.494309,0.007542,0.234303,...,7.656873,166.147093,27.082103,1971.005136,84.402258,98077.939805,47.560053,-122.213896,184.556944,1186.229495
min,1.000102e+06,2014-05-02 00:00:00,7.500000e+04,0.000000,0.000000,26.941908,48.309628,1.000000,0.000000,0.000000,...,1.000000,26.941908,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,37.068349,60.479938
25%,2.123049e+09,2014-07-22 00:00:00,3.219500e+05,3.000000,1.750000,132.572766,468.231775,1.000000,0.000000,0.000000,...,7.000000,110.554725,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,138.425664,473.805963
50%,3.904930e+09,2014-10-16 00:00:00,4.500000e+05,3.000000,2.250000,177.444978,707.736044,1.500000,0.000000,0.000000,...,7.000000,144.928883,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,170.941759,707.921851
75%,7.308900e+09,2015-02-17 00:00:00,6.450000e+05,4.000000,2.500000,236.902981,992.948653,2.000000,0.000000,0.000000,...,8.000000,205.315917,52.025753,1997.000000,0.000000,98118.000000,47.678000,-122.125000,219.251387,936.742260
max,9.900000e+09,2015-05-27 00:00:00,7.700000e+06,33.000000,8.000000,1257.908380,153416.419842,3.500000,1.000000,4.000000,...,13.000000,874.218453,447.793087,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,576.928437,80937.206850
std,2.876570e+09,NaN,3.671268e+05,0.930105,0.770163,85.326034,3848.095166,0.539989,0.086517,0.766318,...,1.175459,76.932244,41.116607,29.373411,401.679240,53.505026,0.138564,0.140828,63.674997,2536.643750

### Padronização de variáveis categóricas

In [12]:
#Convertendo para metros quadrados e traduzindo
mapeamento_colunas = {
    'id': 'id',
    'date': 'data',
    'price': 'preco',
    'bedrooms': 'quartos',
    'bathrooms': 'banheiros',
    'sqft_living': 'area_habitavel_m2',
    'sqft_lot': 'area_lote_m2',
    'floors': 'andares',
    'waterfront': 'vista_mar',
    'view': 'qualidade_vista',
    'condition': 'condicao_imovel',
    'grade': 'nota_design',
    'sqft_above': 'area_acima_solo_m2',
    'sqft_basement': 'area_porao_m2',
    'yr_built': 'ano_construcao',
    'yr_renovated': 'ano_reforma',
    'zipcode': 'cep',
    'lat': 'latitude',
    'long': 'longitude',
    'sqft_living15': 'area_habitavel_vizinhos_15_em_m2',
    'sqft_lot15': 'area_lote_vizinhos_15_em_m2'
}

# Aplicando a renomeação
df_traduzido= df.rename(columns=mapeamento_colunas)
# Verificando se deu certo
print("Colunas renomeadas com sucesso:")
print(df_traduzido.columns.tolist())

Colunas renomeadas com sucesso:
['id', 'data', 'preco', 'quartos', 'banheiros', 'area_habitavel_m2', 'area_lote_m2', 'andares', 'vista_mar', 'qualidade_vista', 'condicao_imovel', 'nota_design', 'area_acima_solo_m2', 'area_porao_m2', 'ano_construcao', 'ano_reforma', 'cep', 'latitude', 'longitude', 'area_habitavel_vizinhos_15_em_m2', 'area_lote_vizinhos_15_em_m2']

In [13]:
df_traduzido.head()

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,nota_design,area_acima_solo_m2,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2
0,7229300521,2014-10-13,231300.0,2,1.00,109.625693,524.902684,1.0,0,0,...,7,109.625693,0.000000,1955,0,98178,47.5112,-122.257,124.490194,524.902684
1,6414100192,2014-12-09,538000.0,3,2.25,238.761044,672.804467,2.0,0,0,...,7,201.599792,37.161252,1951,1991,98125,47.7210,-122.319,157.006290,709.687010
2,5631500400,2015-02-25,180000.0,2,1.00,71.535410,929.031300,1.0,0,0,...,6,71.535410,0.000000,1933,0,98028,47.7379,-122.233,252.696514,748.985034
3,2487200875,2014-12-09,604000.0,4,3.00,182.090135,464.515650,1.0,0,0,...,7,97.548286,84.541848,1965,0,98136,47.5208,-122.393,126.348257,464.515650
4,1954400510,2015-02-18,510000.0,3,2.00,156.077258,750.657290,1.0,0,0,...,8,156.077258,0.000000,1987,0,98074,47.6168,-122.045,167.225634,697.052184

In [14]:
df_traduzido[df_traduzido['quartos']>10]

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,nota_design,area_acima_solo_m2,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2
8757,1773100755,2014-08-21,520000.0,11,3.00,278.709390,460.799525,2.0,0,0,...,7,222.967512,55.741878,1918,1999,98106,47.5560,-122.363,131.922445,460.799525
15870,2402100895,2014-06-25,640000.0,33,1.75,150.503071,557.418780,1.0,0,0,...,7,96.619255,53.883815,1947,0,98103,47.6878,-122.331,123.561163,436.644711

In [15]:
df_traduzido= df_traduzido.drop(df_traduzido[df_traduzido['quartos']>30].index)

In [16]:
df_traduzido.describe()

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,nota_design,area_acima_solo_m2,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2
count,2.161200e+04,21612,2.161200e+04,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,...,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000
mean,4.580407e+09,2014-10-29 04:46:26.451971,5.400840e+05,3.369424,2.114774,193.231173,1403.523720,1.494332,0.007542,0.234314,...,7.656904,166.150310,27.080863,1971.006247,84.406163,98077.938645,47.560047,-122.213891,184.559767,1186.264179
min,1.000102e+06,2014-05-02 00:00:00,7.500000e+04,0.000000,0.000000,26.941908,48.309628,1.000000,0.000000,0.000000,...,1.000000,26.941908,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,37.068349,60.479938
25%,2.123049e+09,2014-07-22 00:00:00,3.218375e+05,3.000000,1.750000,132.526315,468.231775,1.000000,0.000000,0.000000,...,7.000000,110.554725,0.000000,1951.000000,0.000000,98033.000000,47.470975,-122.328000,138.425664,473.805963
50%,3.904930e+09,2014-10-16 00:00:00,4.500000e+05,3.000000,2.250000,177.444978,707.828947,1.500000,0.000000,0.000000,...,7.000000,144.928883,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,170.941759,707.921851
75%,7.308900e+09,2015-02-17 00:00:00,6.450000e+05,4.000000,2.500000,236.902981,992.971879,2.000000,0.000000,0.000000,...,8.000000,205.315917,52.025753,1997.000000,0.000000,98118.000000,47.678000,-122.125000,219.251387,936.765485
max,9.900000e+09,2015-05-27 00:00:00,7.700000e+06,11.000000,8.000000,1257.908380,153416.419842,3.500000,1.000000,4.000000,...,13.000000,874.218453,447.793087,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,576.928437,80937.206850
std,2.876598e+09,NaN,3.671347e+05,0.908026,0.770177,85.327513,3848.179892,0.539991,0.086519,0.766334,...,1.175477,76.932570,41.117154,29.373636,401.688123,53.505993,0.138564,0.140829,63.675119,2536.697313

In [17]:
df_traduzido.info()

<class 'pandas.DataFrame'>
Index: 21612 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                21612 non-null  int64
 1   data                              21612 non-null  datetime64[us]
 2   preco                             21612 non-null  float64
 3   quartos                           21612 non-null  int64
 4   banheiros                         21612 non-null  float64
 5   area_habitavel_m2                 21612 non-null  float64
 6   area_lote_m2                      21612 non-null  float64
 7   andares                           21612 non-null  float64
 8   vista_mar                         21612 non-null  int64
 9   qualidade_vista                   21612 non-null  int64
 10  condicao_imovel                   21612 non-null  int64
 11  nota_design                       21612 non-null  int64
 12  area_acima_solo_m2                21612 non-null  float64
 13  area_porao_m2                     21612 non-null  float64
 14  ano_construcao                    21612 non-null  int64
 15  ano_reforma                       21612 non-null  int64
 16  cep                               21612 non-null  int64
 17  latitude                          21612 non-null  float64
 18  longitude                         21612 non-null  float64
 19  area_habitavel_vizinhos_15_em_m2  21612 non-null  float64
 20  area_lote_vizinhos_15_em_m2       21612 non-null  float64
dtypes: datetime64[us](1), float64(11), int64(9)
memory usage: 3.6 MB

In [18]:
for col in ['vista_mar', 'qualidade_vista', 'condicao_imovel', 'nota_design', 'andares', 'quartos']:
    print(f'{col}: {sorted(df_traduzido[col].unique())}')

vista_mar: [np.int64(0), np.int64(1)]
qualidade_vista: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
condicao_imovel: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
nota_design: [np.int64(1), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
andares: [np.float64(1.0), np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0), np.float64(3.5)]
quartos: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11)]

---
## 🔹 FASE 2 — Consultas e Agregações

### 4. Análise Histórica de Preços

In [19]:
df_traduzido['ANO'] = df_traduzido['data'].dt.year
df_traduzido['MES'] = df_traduzido['data'].dt.month

In [20]:
df_traduzido.head()

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2,ANO,MES
0,7229300521,2014-10-13,231300.0,2,1.00,109.625693,524.902684,1.0,0,0,...,0.000000,1955,0,98178,47.5112,-122.257,124.490194,524.902684,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.761044,672.804467,2.0,0,0,...,37.161252,1951,1991,98125,47.7210,-122.319,157.006290,709.687010,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.535410,929.031300,1.0,0,0,...,0.000000,1933,0,98028,47.7379,-122.233,252.696514,748.985034,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.090135,464.515650,1.0,0,0,...,84.541848,1965,0,98136,47.5208,-122.393,126.348257,464.515650,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.077258,750.657290,1.0,0,0,...,0.000000,1987,0,98074,47.6168,-122.045,167.225634,697.052184,2015,2

In [21]:
media_preco_ano = df_traduzido.groupby('ANO')['preco'].mean().round(2).reset_index().rename(columns={'preco' : 'Média de Preço'})
media_preco_ano

    ANO  Média de Preço
0  2014       539175.18
1  2015       541988.99

In [22]:
media_mensal_geral = df_traduzido.groupby(['ANO','MES'])['preco'].mean().reset_index().round(2)
media_mensal_geral

     ANO  MES      preco
0   2014    5  548080.28
1   2014    6  557964.57
2   2014    7  544788.76
3   2014    8  536445.28
4   2014    9  529253.82
5   2014   10  539031.98
6   2014   11  521961.01
7   2014   12  524461.87
8   2015    1  525870.89
9   2015    2  507851.37
10  2015    3  543977.19
11  2015    4  561837.77
12  2015    5  558126.81

In [23]:
#Gráfico de linha no periodo do datset 
media_mensal_geral['data_referencia'] = pd.to_datetime(media_mensal_geral['ANO'].astype(str)+ '-' +media_mensal_geral['MES'].astype(str) + '-01')

fig = px.line(media_mensal_geral , x ='data_referencia', y = 'preco', color='ANO', color_discrete_map={2014:'blue' , 2015:'red'} 
              , title = 'Comportamento de Preços: 2014 (Azul) vs 2015 (Vermelho)', markers =True)

fig.update_xaxes(
    dtick = 'M1',
    tickformat='%b\n%Y',
    ticklabelmode="period"

)
fig.show()

### 5 Análise Localizada

In [24]:
cep_diferentes=df_traduzido['cep'].unique()
cep_diferentes

array([98178, 98125, 98028, 98136, 98074, 98053, 98003, 98198, 98146,
       98038, 98007, 98115, 98107, 98126, 98019, 98103, 98002, 98133,
       98040, 98092, 98030, 98119, 98112, 98052, 98027, 98117, 98058,
       98001, 98056, 98166, 98023, 98070, 98148, 98105, 98042, 98008,
       98059, 98122, 98144, 98004, 98005, 98034, 98075, 98116, 98010,
       98118, 98199, 98032, 98045, 98102, 98077, 98108, 98168, 98177,
       98065, 98029, 98006, 98109, 98022, 98033, 98155, 98024, 98011,
       98031, 98106, 98072, 98188, 98014, 98055, 98039])

In [25]:
#CEps que mais aparecem
contagem_ceps= df_traduzido['cep'].value_counts().reset_index()

contagem_ceps.rename(columns = {'count' :'Frequêcia'})

contagem_ceps

      cep  count
0   98103    601
1   98038    590
2   98115    583
3   98052    574
4   98117    553
..    ...    ...
65  98102    105
66  98010    100
67  98024     81
68  98148     57
69  98039     50

[70 rows x 2 columns]

In [26]:
# utilizando o bairro com mais dados no dataset
cep_escolhido = 98103
df_bairro = df_traduzido[df_traduzido['cep'] == cep_escolhido]
preco_maximo = df_bairro['preco'].max()
preco_minimo = df_bairro['preco'].min()

print(f'O maior valor para o bairro de cep {cep_escolhido} foi R${preco_maximo:.2f} e o menor foi R${preco_minimo:.2f}')
#print(maior)

O maior valor para o bairro de cep 98103 foi R$1695000.00 e o menor foi R$238000.00

### 6 Ranking de Bairros

In [27]:
# Tabela com os cinco bairros com maior preço mediano
bairros_mediana=df_traduzido.groupby('cep')['preco'].median().reset_index().rename(columns={'preco' : 'mediana preco'}).round(2).sort_values(by='mediana preco' , ascending = False)
bairros_mediana_top5= bairros_mediana.head(5)
bairros_mediana_top5
#print(f'Os 5 bairros com maiores valores de preço são ')

      cep  mediana preco
24  98039      1892500.0
3   98004      1150000.0
25  98040       993750.0
48  98112       915000.0
4   98005       765475.0

In [28]:
bairros_mediana

      cep  mediana preco
24  98039      1892500.0
3   98004      1150000.0
25  98040       993750.0
48  98112       915000.0
4   98005       765475.0
..    ...            ...
67  98188       264000.0
0   98001       260000.0
20  98032       249000.0
1   98002       235000.0
64  98168       235000.0

[70 rows x 2 columns]

In [29]:
fig0 = px.bar(bairros_mediana_top5,
              y='cep',
              x = 'mediana preco',
              orientation= 'h',
              title= 'Top 5 CEPs pela mediana de Preço',
              text_auto= '.3s',
              color='mediana preco',
              color_continuous_scale='Viridis')
fig0.update_yaxes(type='category')
fig0.show()

In [30]:
media_preco_bairros=(
    df_traduzido.groupby('cep')['preco']
    .mean()
    .sort_values(ascending=False)
    .to_frame()
    .rename(columns={'preco': 'Média de precos'})
    .reset_index()
    .round(2)
)
top_5_ceps = media_preco_bairros.head(5)
top_5_ceps['cep'] = top_5_ceps['cep'].astype(str)
top_5_ceps

     cep  Média de precos
0  98039       2160606.60
1  98004       1355927.08
2  98040       1194230.02
3  98112       1095499.34
4  98102        901258.27

In [31]:
media_preco_bairros

      cep  Média de precos
0   98039       2160606.60
1   98004       1355927.08
2   98040       1194230.02
3   98112       1095499.34
4   98102        901258.27
..    ...              ...
65  98148        284908.60
66  98001        280804.69
67  98032        251296.24
68  98168        240328.37
69  98002        234284.04

[70 rows x 2 columns]

In [32]:
# 4. Gráfico de barras horizontais (y='cep')
fig = px.bar(top_5_ceps, 
             y='cep', 
             x='Média de precos', 
             orientation='h', # Barra horizontal é mais elegante aqui
             title='Top 5 CEPs pela Media de Preço',
             text_auto='.3s',
             color='Média de precos',
             color_continuous_scale='Viridis')

fig.update_yaxes(type='category') 
fig.show()

In [33]:
lista_dos_ceps_mais_caros = top_5_ceps['cep'].astype(int).to_list()
lista_dos_ceps_mais_caros

[98039, 98004, 98040, 98112, 98102]

In [34]:
# Se o CEP estiver na lista dos top 5, recebe 'Top 5', caso contrário 'Demais Localidades'
df_traduzido['categoria_mapa'] = df_traduzido['cep'].apply(
    lambda x: 'Top 5 Mais Caros' if x in lista_dos_ceps_mais_caros else 'Outros'
)

# 3. Plotar o mapa usando a nova coluna para a cor
fig = px.scatter_mapbox(
    df_traduzido, 
    lat="latitude", 
    lon="longitude", 
    color="categoria_mapa", # A cor agora é baseada na categoria (Top 5 vs Outros)
    size="preco",           # O tamanho continua sendo o preço para dar volume
    color_discrete_map={'Top 5 Mais Caros': 'red', 'Outros': 'blue'}, # Cores manuais para destaque
    zoom=9,
    mapbox_style="carto-positron",
    title="Destaque Geográfico: Os 5 CEPs com Maiores Médias de Preço"
)

fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
fig.show()

/tmp/ipykernel_11655/2716326008.py:7: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(

In [35]:
# Usando o mapa de densidade ou de pontos para verificar o comportamento de todos os bairros no geral
fig = px.scatter_mapbox(df_traduzido, 
                        lat="latitude", 
                        lon="longitude", 
                        color="preco", 
                        size="preco",
                        color_continuous_scale=px.colors.cyclical.IceFire, 
                        size_max=15, 
                        zoom=10,
                        mapbox_style="carto-positron",#Mapa de código aberto sem API 
                        title="Distribuição Geográfica de Preços")

fig.show()

/tmp/ipykernel_11655/1860272305.py:2: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(df_traduzido,

In [36]:
#df apenas com os bairros TOP 5
df_top5_bairros = df_traduzido[df_traduzido['cep'].isin(lista_dos_ceps_mais_caros)]
df_top5_bairros

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2,ANO,MES,categoria_mapa
21,2524049179,2014-08-26,2000000.0,3,2.75,283.354546,4168.284733,1.0,0,4,...,1968,0,98040,47.5316,-122.233,381.831864,1889.278052,2014,8,Top 5 Mais Caros
27,3303700376,2014-12-01,667000.0,3,1.00,130.064382,146.879849,1.5,0,0,...,1909,0,98112,47.6221,-122.314,172.799822,358.698985,2014,12,Top 5 Mais Caros
66,3394100030,2014-09-09,975000.0,4,2.50,252.696514,1026.486683,2.0,0,0,...,1989,0,98004,47.5815,-122.192,255.483607,1026.486683,2014,9,Top 5 Mais Caros
69,1802000060,2014-06-12,1325000.0,5,2.25,297.290016,1872.741294,1.0,0,0,...,1965,0,98004,47.6303,-122.215,314.941611,1872.741294,2014,6,Top 5 Mais Caros
95,1483300570,2014-09-08,905000.0,4,2.50,306.580329,952.257082,1.0,0,0,...,1946,1991,98040,47.5873,-122.249,181.161103,561.599421,2014,9,Top 5 Mais Caros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21552,688000017,2014-06-27,516500.0,1,1.25,102.193443,59.272197,3.0,0,0,...,2014,0,98112,47.6228,-122.307,103.122474,179.581750,2014,6,Top 5 Mais Caros
21568,524059330,2015-01-30,1700000.0,4,3.50,355.818988,832.690754,2.0,0,0,...,2014,0,98004,47.5990,-122.197,203.457855,1001.217032,2015,1,Top 5 Mais Caros
21583,2025049203,2014-06-10,399950.0,2,1.00,65.961222,107.488921,2.0,0,0,...,1943,0,98102,47.6413,-122.329,127.277288,108.975371,2014,6,Top 5 Mais Caros
21597,191100405,2015-04-21,1575000.0,4,3.25,316.799673,940.644191,2.0,0,0,...,2007,0,98040,47.5653,-122.223,212.748168,940.644191,2015,4,Top 5 Mais Caros
21600,249000205,2014-10-15,1537000.0,5,3.75,415.276991,751.400515,2.0,0,0,...,2008,0,98004,47.6321,-122.200,258.270701,832.783657,2014,10,Top 5 Mais Caros

In [37]:
#Discutindo Sobre os Motivos Dos Preços altos

#média vista para água no top 5
vista_agua_top5= df_top5_bairros['vista_mar'].mean()*100

vista_agua_total = df_traduzido['vista_mar'].mean()*100

print(f"Porcentagem de casas com vista para água no Top 5: {vista_agua_top5:.2f}%")
print(f"Porcentagem de casas com vista para água no Total: {vista_agua_total:.2f}%")

Porcentagem de casas com vista para água no Top 5: 1.37%
Porcentagem de casas com vista para água no Total: 0.75%

In [38]:
# Comparando a nota média de construção
grade_top5 = df_top5_bairros['qualidade_vista'].mean()
grade_total = df_traduzido['qualidade_vista'].mean()

print(f"Qualidade média das casas no Top 5: {grade_top5:.2f}")
print(f"Qualidade média das casas no Total: {grade_total:.2f}")

Qualidade média das casas no Top 5: 0.39
Qualidade média das casas no Total: 0.23

In [39]:
# Comparando a área habitável média (m²)
area_top5 = df_top5_bairros['area_habitavel_m2'].mean()
area_total = df_traduzido['area_habitavel_m2'].mean()

print(f"Área média no Top 5: {area_top5:.2f} m²")
print(f"Área média no Total: {area_total:.2f} m²")

Área média no Top 5: 262.21 m²
Área média no Total: 193.23 m²

In [40]:
preco_medio_top5= df_top5_bairros['preco'].mean()
preco_medio_total= df_traduzido['preco'].mean()
print(f'Preço médio no top5: {preco_medio_top5:.2f}')
print(f'Preço médio total: {preco_medio_total:.2f}')

Preço médio no top5: 1235536.19
Preço médio total: 540083.95

## 🔹 FASE 3 — Consultas e Agregações

### 7 Indentificação de Outliers

In [41]:
fig_hist = px.histogram(
    df_traduzido,
    x = 'preco',
    nbins= 100,
    histnorm= 'probability density',
    title= 'Distribuição dos Preços'
)
fig_hist.show()

In [42]:
df_traduzido['log_preco'] = np.log(df_traduzido['preco'])

fig_hist_log = px.histogram(
    df_traduzido,
    x = 'log_preco',
    nbins=100,
    histnorm='probability density',
    title= 'Distribuição do log(preco)'
)
fig_hist_log.show()

In [43]:
fig_box= px.box(df_traduzido,
                y='preco',
                title = 'Distribuição de Preços com outliers',
                points='outliers'
                )
fig_box.show()

In [44]:
#Mais eficiente para outliers maiores do que a mediana

Q1 = df_traduzido['preco'].quantile(0.25)
Q3 = df_traduzido['preco'].quantile(0.75)

IQR = Q3-Q1

limite_inferior = Q1 - 1.5*IQR
limite_superior = Q3 +1.5*IQR


print(f'Q1: {Q1:,.0f}')
print(f'Q3: {Q3:,.0f}')
print(f'IQR: {IQR:,.0f}')
print(f'Limite superior: {limite_superior:,.0f}')
print(f'Limite inferior: {limite_inferior:,.0f}')

df_traduzido['classificacao']  = df_traduzido['preco'].apply(
    lambda x: 'Outlier' if x > limite_superior or x < limite_inferior else 'Normal'
)

total = len(df_traduzido)
n_outliers = (df_traduzido['classificacao'] == 'Outlier').sum()
print(f'\nOutliers encontrados: {n_outliers} ({n_outliers/total*100:.1f}%)')

Q1: 321,838
Q3: 645,000
IQR: 323,162
Limite superior: 1,129,744
Limite inferior: -162,906

Outliers encontrados: 1146 (5.3%)

In [45]:
fig4 = px.scatter_mapbox(
    df_traduzido,
    lat='latitude',
    lon='longitude',
    color=df_traduzido['preco'].apply(
        lambda x: 'Outlier' if x > limite_superior else 'Normal'
    ),
    color_discrete_map={'Outlier': 'red', 'Normal': 'steelblue'},
    size='preco',
    zoom=9,
    mapbox_style='carto-positron',
    title='Localização Geográfica dos Outliers de Preço'
)
fig4.show()

/tmp/ipykernel_11655/1626091760.py:1: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig4 = px.scatter_mapbox(

In [ ]:
#Utilizando o z score com,og para identificar os outliers
media_log = df_traduzido['log_preco'].mean()
desvio_log= df_traduzido['log_preco'].std()

# (valor - média) / desvio padrãoárea
# np.abs() pega o valor absoluto 

df_traduzido['z_score'] = (df_traduzido['log_preco'] - media_log)/desvio_log
df_traduzido['z_score_abs'] = df_traduzido['z_score'].abs()

df_traduzido['classificacao_z'] = df_traduzido['z_score_abs'].apply(
    lambda z: 'Outlier' if z > 3 else 'Normal'
)
n_outliers_z = (df_traduzido['classificacao_z'] == 'Outlier').sum()
print(f'Outliers pelo Z-Score: {n_outliers_z} ({n_outliers_z/total*100:.1f}%)')

Outliers pelo Z-Score: 170 (0.8%)

In [48]:
outliers = df_traduzido[df_traduzido['classificacao_z'] == 'Outlier']
normais  = df_traduzido[df_traduzido['classificacao_z'] == 'Normal']

total = len(df_traduzido)
n_out = len(outliers)

print(f'Total de imóveis:  {total}')
print(f'Outliers:          {n_out} ({n_out/total*100:.1f}%)')
print(f'Normais:           {len(normais)}')
print(f'\nZ-score máximo:    {df_traduzido["z_score_abs"].max():.2f}')
print(f'Z-score mínimo:    {df_traduzido["z_score_abs"].min():.2f}')
print(f'\nPreço mais alto entre outliers:  {outliers["preco"].max():,.0f}')
print(f'Preço mais baixo entre outliers: {outliers["preco"].min():,.0f}')

Total de imóveis:  21612
Outliers:          170 (0.8%)
Normais:           21442

Z-score máximo:    5.33
Z-score mínimo:    0.00

Preço mais alto entre outliers:  7,700,000
Preço mais baixo entre outliers: 75,000

In [ ]:
corte_superior = media_log + 3 * desvio_log
corte_inferior = media_log - 3 * desvio_log

fig = px.histogram(
    df_traduzido,
    x='log_preco',
    nbins=100,
    color='classificacao_z',                               # colore por classificação
    color_discrete_map={'Outlier': 'red', 'Normal': 'steelblue'},
    title='Distribuição do Log(Preço) — Outliers pelo Z-Score',área
    labels={'log_preco': 'Log(Preço)', 'outlier_z': 'Classificação'},
    opacity=0.8
)

# linha vertical no corte superior
fig.add_vline(
    x=corte_superior,
    line_dash='dash',
    line_color='darkred',
    annotation_text=f'z = +3  ({np.exp(corte_superior):,.0f})',  # mostra o preço real
    annotation_position='top left'
)

# linha vertical no corte inferior
fig.add_vline(
    x=corte_inferior,
    line_dash='dash',
    line_color='darkblue',
    annotation_text=f'z = -3  ({np.exp(corte_inferior):,.0f})',
    annotation_position='top right'
)

fig.show()

In [52]:
fig = px.box(
    df_traduzido,
    y='preco',
    color='classificacao_z',
    color_discrete_map={'Outlier': 'red', 'Normal': 'steelblue'},
    title='Boxplot de Preços — Outliers pelo Z-Score',
    labels={'preco': 'Preço', 'outlier_z': 'Classificação'},
    points='outliers'   # mostra só os pontos que são outliers, não todos
)

fig.show()

In [57]:
fig = px.scatter(
    df_traduzido,
    x='preco',
    y='z_score',                                     # eixo Y é o z-score
    color='classificacao_z',
    color_discrete_map={'Outlier': 'red', 'Normal': 'steelblue'},
    opacity=0.5,
    title='Z-Score vs Preço — Onde Cada Imóvel Está',
    labels={
        'preco': 'Preço',
        'z_score': 'Z-Score',
        'outlier_z': 'Classificação'
    },
    hover_data=['quartos', 'nota_design', 'vista_mar', 'cep']
)

# linhas horizontais nos limiares
fig.add_hline(y=3,  line_dash='dash', line_color='darkred',
              annotation_text='z = +3')
fig.add_hline(y=-3, line_dash='dash', line_color='darkblue',
              annotation_text='z = -3')
fig.add_hline(y=0,  line_dash='dot',  line_color='gray',
              annotation_text='média')

fig.show()

In [58]:
colunas = [
    'preco', 'z_score_abs', 'area_habitavel_m2',
    'quartos', 'nota_design', 'condicao_imovel', 'vista_mar', 'cep'
]

tabela_outliers = (
    df_traduzido[df_traduzido['classificacao_z'] == 'Outlier']
    [colunas]
    .sort_values('z_score_abs', ascending=False)  # ordena pelo mais extremo
    .reset_index(drop=True)
)

print(f'Total de outliers: {len(tabela_outliers)}')
print()
print(tabela_outliers.to_string())

Total de outliers: 170

         preco  z_score_abs  area_habitavel_m2  quartos  nota_design  condicao_imovel  vista_mar    cep
0    7700000.0     5.333174        1119.482716        6           13                4          0  98102
1    7062500.0     5.169090         932.747425        5           11                3          1  98004
2    6885000.0     5.120762         918.811956        6           13                3          0  98039
3    5570000.0     4.718342         854.708796        5           13                3          0  98039
4    5350000.0     4.641830         743.225040        5           12                3          0  98004
5    5300000.0     4.624002         686.554131        6           12                4          1  98040
6    5110800.0     4.554984         744.154071        5           12                3          1  98033
7    4668000.0     4.382918         895.586173        5           12                3          1  98040
8    4500000.0     4.313326         616.876783        5           12                3          1  98155
9    4489000.0     4.308680         597.367126        4           12                3          0  98004
10   4208000.0     4.185946         691.199287        5           12                3          0  98006
11   4000000.0     4.089698         657.754160        4           12                3          0  98039
12   3850000.0     4.017129         536.051060        4           11                4          1  98040
13   3800000.0     3.992309         654.967066        5           13                4          0  98004
14   3800000.0     3.992309         511.896246        3           13                3          0  98177
15   3710000.0     3.946800         515.612371        4           12                4          0  98039
16   3650000.0     3.915843         466.373713        5           12                3          0  98004
17   3650000.0     3.915843         509.109152        6           11                5          1  98105
18   3640900.0     3.911104         448.722118        4           11                4          1  98039
19   3635000.0     3.908025         510.038184        5           12                3          0  98039
20   3600000.0     3.889655         466.373713        3           10                3          1  98144
21   3567000.0     3.872170         450.580180        5           10                3          1  98008
22   3418800.0     3.791600         506.322058        5           11                3          0  98039
23   3400000.0     3.781131         395.767334        4           11                3          0  98112
24   3400000.0     3.781131         485.883370        3           10                3          1  98040
25   3395000.0     3.778336         439.431805        4           10                3          1  98033
26   3345000.0     3.750166         497.031745        5           11                3          0  98004
27   3300000.0     3.724450         392.051209        3           11                4          1  98008
28   3300000.0     3.724450         745.083103        5           11                3          0  98006
29   3300000.0     3.724450         575.999406        5           11                4          1  98008
30   3300000.0     3.724450         716.283132        8           12                5          0  98112
31   3278000.0     3.711750         635.457409        2           11                3          1  98008
32   3204000.0     3.668397         446.864055        4           11                3          0  98004
33   3200000.0     3.666026         659.612223        6           13                3          0  98199
34   3200000.0     3.666026         423.638273        3           11                3          0  98004
35   3200000.0     3.666026         650.321910        4           12                4          1  98075
36   3200000.0     3.666026         576.928437        7           11                5          0  98109
37   3168750.0     3.647393         402.270553        5           12                3          0  98004
38   3120000.0     3.617956         417.135054        3           12                3          1  98034
39   3100000.0     3.605746         648.463847        6           12                4          0  98040
40   3100000.0     3.605746         364.180270        3           11                4          1  98040
41   3100000.0     3.605746         472.876932        5           12                3          0  98004
42   3075000.0     3.590372         422.709241        4           10                3          1  98074
43   3070000.0     3.587282         365.109301        3            8                4          1  98034
44   3065000.0     3.584188         385.547989        5           11                5          0  98119
45   3000000.0     3.543489         450.580180        4           10                5          1  98034
46   3000000.0     3.543489         409.702803        3           11                3          1  98056
47   3000000.0     3.543489         472.876932        4           11                3          0  98004
48   3000000.0     3.543489         498.889808        5           10                3          0  98004
49   3000000.0     3.543489         426.425367        5           11                4          0  98112
50   2998000.0     3.542223         619.663877        5           12                3          0  98004
51   2983000.0     3.532700         687.483162        5           13                3          0  98006
52   2950000.0     3.511579         415.276991        4           11                3          0  98199
53   2950000.0     3.511579         361.393176        4           10                5          1  98105
54   2950000.0     3.511579         579.715531        5           11                3          0  98040
55   2950000.0     3.511579         451.509212        4           12                3          0  98039
56   2945000.0     3.508358         403.199584        5           10                3          0  98107
57   2920000.0     3.492171         425.031820        4           10                5          0  98112
58   2903000.0     3.481085         348.386737        5           10                3          1  98118
59   2900000.0     3.479122         482.167245        5           11                3          0  98039
60   2900000.0     3.479122         425.496335        4           11                4          0  98109
61   2900000.0     3.479122         469.160806        4           11                3          0  98004
62   2890000.0     3.472564         536.980091        4           11                3          0  98112
63   2888000.0     3.471249         805.470137        5           13                3          0  98177
64   2885000.0     3.469276         497.031745        7           10                4          0  98112
65   2880500.0     3.466312         535.122029        4           12                4          0  98177
66     75000.0     3.460408          62.245097        1            3                3          0  98022
67   2850000.0     3.446101         468.231775        4           10                5          0  98006
68   2795000.0     3.409103         426.425367        5           11                5          0  98199
69     78000.0     3.385941          72.464441        2            5                1          0  98168
70   2750000.0     3.378285         585.289719        5           12                3          0  98004
71   2750000.0     3.378285         411.560866        4           10                3          0  98039
72   2750000.0     3.378285         383.689927        4           10                4          1  98075
73   2725000.0     3.360946         595.509063        4           12                4          0  98144
74   2720000.0     3.357459         370.683489        4           11                4          0  98039
75   2700000.0     3.343447         492.851105        5           11                3          0  98033
76   2700000.0     3.343447         410.631835        4           11                3          1  98008
77   2700000.0     3.343447         729.289570        4           12                3          0  98027
78   2700000.0     3.343447         392.980240        5            8                3          1  98033
79   2700000.0     3.343447         355.911891        5            9                3          1  98040
80     80000.0     3.337872          39.948346        1            4                2          0  98014
81   2680000.0     3.329330         398.554428        5           11                4          0  98039
82     81000.0     3.314285          67.819285        2            5                1          0  98168
83   2650000.0     3.307957         436.644711        4           11                3          0  98033
84   2641100.0     3.301569         432.928586        5           11                3          0  98004
85   2630000.0     3.293573         514.683340        6           11                4          0  98119
86     82000.0     3.290989          79.896692        3            6                3          0  98146
87     82500.0     3.279447          48.309628        2            5                2          0  98168
88   2600000.0     3.271791         316.799673        3           10                4          1  98040
89   2600000.0     3.271791         489.599495        4           11                3          1  98027
90     83000.0     3.267975          83.612817        2            5                3          0  98168
91   2575000.0     3.253446         444.076961        5           10                4          0  98039
92   2575000.0     3.253446         514.683340        4           11                3          0  98004
93   2575000.0     3.253446         304.722266        4           11                3          0  98112
94   2574000.0     3.252709         415.741507        4           12                3          1  98033
95     84000.0     3.245236          65.032191        2            6                3          0  98168
96   2555000.0     3.238642         492.386589        4           10                2          1  98105
97   2546000.0     3.231942         389.264115        4            9                5          0  98112
98   2544750.0     3.231010         502.605933        5           10                4          0  98112
99   2538000.0     3.225967         404.128615        4           10                5          0  98112
100  2537000.0     3.225218         344.670612        4           10                5          0  98105
101  2535000.0     3.223721         346.528675        5           10                4          0  98004
102    85000.0     3.222766          77.109598        2            6                3          0  98032
103    85000.0     3.222766          84.541848        2            5                3          0  98032
104  2532000.0     3.221473         468.231775        4           10                3          0  98105
105  2525000.0     3.216217         643.818691        4           11                4          0  98006
106  2510000.0     3.204904         509.109152        3           11                3          1  98166
107  2500000.0     3.197324         522.115591        5           11                4          0  98144
108  2500000.0     3.197324         323.302892        4            9                3          0  98004
109  2500000.0     3.197324         399.483459        4           11                3          0  98039
110  2500000.0     3.197324         367.896395        4           12                3          0  98105
111  2500000.0     3.197324         309.367423        4           10                4          0  98006
112    86500.0     3.189553          78.038629        3            6                3          0  98023
113  2485000.0     3.185898         319.586767        4           10                5          1  98040
114  2480000.0     3.182074         493.315620        4           12                3          0  98006
115  2479000.0     3.181308         632.670315        5           13                3          0  98102
116  2475000.0     3.178242         403.199584        3           11                3          0  98107
117  2466350.0     3.171595         593.651001        5           10                3          0  98112
118  2458000.0     3.165156         603.870345        4           11                3          0  98039
119  2453500.0     3.161677         439.431805        4           10                5          0  98112
120  2450000.0     3.158966         411.560866        5           10                3          0  98004
121  2450000.0     3.158966         394.838302        4           10                4          0  98144
122  2450000.0     3.158966         433.857617        7           11                3          0  98039
123  2450000.0     3.158966         467.302744        4           11                3          0  98040
124    89000.0     3.135457          83.612817        3            6                4          0  98023
125  2415000.0     3.131647         732.076664        5           13                3          0  98177
126  2408000.0     3.126136         427.354398        5            9                3          0  98004
127  2400000.0     3.119818         384.618958        4           10                3          0  98004
128  2400000.0     3.119818         316.799673        5            9                3          0  98119
129  2400000.0     3.119818         544.412342        4           10                5          0  98112
130  2400000.0     3.119818         339.096424        4            9                3          1  98074
131  2400000.0     3.119818         379.973802        4           11                4          0  98102
132  2400000.0     3.119818         454.296306        4           11                3          0  98040
133  2400000.0     3.119818         278.709390        3           11                3          1  98075
134  2400000.0     3.119818         509.109152        6            9                4          0  98119
135  2395000.0     3.115858         353.031894        4           10                3          0  98006
136    89950.0     3.115298          52.954784        1            5                3          0  98146
137    90000.0     3.114243          52.025753        1            4                3          0  98106
138    90000.0     3.114243          72.464441        1            5                3          0  98108
139    90000.0     3.114243          73.393473        2            7                3          0  98034
140    90000.0     3.114243          91.045067        3            6                4          0  98092
141    90000.0     3.114243          53.883815        2            5                3          0  98178
142  2385000.0     3.107914         588.076813        4           13                3          0  98033
143  2384000.0     3.107118         339.096424        5           10                5          0  98119
144  2375000.0     3.099936         299.148079        4           10                3          0  98006
145  2367000.0     3.093530         327.948049        3            9                3          1  98040
146  2351960.0     3.081427         465.444681        4           11                3          0  98040
147  2350000.0     3.079844         515.612371        6           11                3          0  98033
148  2350000.0     3.079844         405.986678        4           10                4          0  98033
149    92000.0     3.072512          70.606379        2            5                3          0  98168
150  2340000.0     3.071748         418.064085        4           13                3          0  98006
151  2328000.0     3.061986         410.631835        4           11                3          0  98004
152  2321000.0     3.056269         536.980091        5           11                3          0  98040
153  2320000.0     3.055450         469.160806        4           11                3          0  98004
154  2300000.0     3.039012         304.722266        4           10                3          0  98119
155  2300000.0     3.039012         405.057647        4           10                3          1  98008
156  2300000.0     3.039012         368.825426        4           11                4          0  98119
157  2300000.0     3.039012         493.315620        7           10                3          0  98004
158  2300000.0     3.039012         381.831864        4           12                3          1  98115
159  2300000.0     3.039012         394.838302        4            9                3          0  98004
160  2300000.0     3.039012         313.083548        4           10                5          0  98112
161  2298000.0     3.037360         378.115739        4           10                3          0  98040
162  2288000.0     3.029080         379.044770        4           11                4          0  98004
163  2280000.0     3.022429        1257.908380        7           12                3          0  98053
164  2271150.0     3.015045         375.328645        4            9                4          0  98039
165    95000.0     3.011588          74.322504        2            7                3          0  98198
166    95000.0     3.011588          99.406349        2            6                2          0  98058
167    95000.0     3.011588          70.606379        1            5                4          0  98002
168    95000.0     3.011588          89.187005        2            4                3          0  98198
169  2260000.0     3.005701         288.928734        3           10                3          0  98004

## 🔹 FASE 4 — Visualização e Análise Exploratória

### 8. Relação entre Área e Preço

In [59]:
fig = px.scatter(
    df_traduzido,
    x='area_habitavel_m2',
    y='preco',
    color='classificacao_z',
    color_discrete_map={'Outlier': 'red', 'Normal': 'steelblue'},
    opacity=0.5,
    title='Preço vs Área — Outliers em Vermelho',
    labels={
        'area_habitavel_m2': 'Área Habitável (m²)',
        'preco': 'Preço',
        'classificacao_z': 'Classificação'
    },
    hover_data=['quartos', 'nota_design', 'vista_mar', 'cep']  # info extra ao passar o mouse
)

fig.show()

In [80]:
#Gráfico de linha no periodo do datset 
media_mensal_geral['data_referencia'] = pd.to_datetime(media_mensal_geral['ANO'].astype(str)+ '-' +media_mensal_geral['MES'].astype(str) + '-01')

fig = px.line(media_mensal_geral , x ='data_referencia', y = 'preco', color='ANO', color_discrete_map={2014:'blue' , 2015:'red'} 
              , title = 'Comportamento de Preços: 2014 (Azul) vs 2015 (Vermelho)', markers =True)

fig.update_xaxes(
    dtick = 'M1',
    tickformat='%b\n%Y',
    ticklabelmode="period"

)
fig.show()

In [69]:
df_traduzido.columns

Index(['id', 'data', 'preco', 'quartos', 'banheiros', 'area_habitavel_m2',
       'area_lote_m2', 'andares', 'vista_mar', 'qualidade_vista',
       'condicao_imovel', 'nota_design', 'area_acima_solo_m2', 'area_porao_m2',
       'ano_construcao', 'ano_reforma', 'cep', 'latitude', 'longitude',
       'area_habitavel_vizinhos_15_em_m2', 'area_lote_vizinhos_15_em_m2',
       'ANO', 'MES', 'categoria_mapa', 'log_preco', 'classificacao', 'z_score',
       'z_score_abs', 'classificacao_z', 'faixa_area'],
      dtype='str')

##  🔹 FASE 5 — Engenharia de Atributos e Correlações

###  11. Criação de Novas Variáveis

In [77]:
df_traduzido

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,area_lote_vizinhos_15_em_m2,ANO,MES,categoria_mapa,log_preco,classificacao,z_score,z_score_abs,classificacao_z,faixa_area
0,7229300521,2014-10-13,231300.0,2,1.00,109.625693,524.902684,1.0,0,0,...,524.902684,2014,10,Outros,12.351471,Normal,-1.322094,1.322094,Normal,80–140m²
1,6414100192,2014-12-09,538000.0,3,2.25,238.761044,672.804467,2.0,0,0,...,709.687010,2014,12,Outros,13.195614,Normal,0.280639,0.280639,Normal,200–280m²
2,5631500400,2015-02-25,180000.0,2,1.00,71.535410,929.031300,1.0,0,0,...,748.985034,2015,2,Outros,12.100712,Normal,-1.798197,1.798197,Normal,Até 80m²
3,2487200875,2014-12-09,604000.0,4,3.00,182.090135,464.515650,1.0,0,0,...,464.515650,2014,12,Outros,13.311329,Normal,0.500343,0.500343,Normal,140–200m²
4,1954400510,2015-02-18,510000.0,3,2.00,156.077258,750.657290,1.0,0,0,...,697.052184,2015,2,Outros,13.142166,Normal,0.179161,0.179161,Normal,140–200m²
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,142.141789,105.073440,3.0,0,0,...,140.190823,2014,5,Outros,12.793859,Normal,-0.482152,0.482152,Normal,140–200m²
21609,6600060120,2015-02-23,400000.0,4,2.50,214.606230,540.045895,2.0,0,0,...,668.902536,2015,2,Outros,12.899220,Normal,-0.282110,0.282110,Normal,200–280m²
21610,1523300141,2014-06-23,402101.0,2,0.75,94.761193,125.419225,2.0,0,0,...,186.456582,2014,6,Outros,12.904459,Normal,-0.272163,0.272163,Normal,80–140m²
21611,291310100,2015-01-16,400000.0,3,2.50,148.645008,221.852674,2.0,0,0,...,119.566328,2015,1,Outros,12.899220,Normal,-0.282110,0.282110,Normal,140–200m²
21612,1523300157,2014-10-15,325000.0,2,0.75,94.761193,99.963768,2.0,0,0,...,126.069547,2014,10,Outros,12.691580,Normal,-0.676344,0.676344,Normal,80–140m²

In [85]:
df_traduzido['preco_por_m2'] = df_traduzido['preco'] / df_traduzido['area_habitavel_m2']
df_traduzido['idade_imovel'] = df_traduzido['data'].dt.year - df_traduzido['ano_construcao']
df_traduzido['razao_area']=df_traduzido['area_habitavel_m2']/df_traduzido['area_lote_m2']
df_traduzido['foi_reformado'] = np.where(df_traduzido['ano_reforma']> 0 , 1 , 0)

novas_colunas = ['preco_por_m2', 'idade_imovel', 'foi_reformado', 'razao_area']
print("Novas variáveis criadas:")
print(df_traduzido[novas_colunas].describe().round(2))

Novas variáveis criadas:
       preco_por_m2  idade_imovel  foi_reformado  razao_area
count      21612.00      21612.00       21612.00    21612.00
mean        2843.29         43.32           0.04        0.32
std         1184.67         29.38           0.20        0.27
min          942.79         -1.00           0.00        0.00
25%         1962.12         18.00           0.00        0.16
50%         2633.14         40.00           0.00        0.25
75%         3426.38         63.00           0.00        0.41
max         8720.25        115.00           1.00        4.65

In [90]:
#top 10 preços por metro quadrado por cep
preco_m2_cep = (df_traduzido.groupby('cep')['preco_por_m2'].mean().reset_index().sort_values('preco_por_m2', ascending=False).head(10).round(2).rename(columns={'preco_por_m2': 'preco_medio_m2'}))
preco_m2_cep

      cep  preco_medio_m2
24  98039         6114.79
3   98004         5117.54
48  98112         4721.45
47  98109         4665.09
53  98119         4652.77
41  98102         4554.99
43  98105         4361.04
25  98040         4168.78
45  98107         4122.06
69  98199         4053.11

In [94]:
fig_preco_m2_cep = px.bar(
    preco_m2_cep,
    x ='cep',
    y= 'preco_medio_m2',
    title='Top 10 CEPS pods M²',
    color = 'preco_medio_m2',
    color_continuous_scale= 'Blues',
    text_auto= '.0f'
)
fig_preco_m2_cep.update_xaxes(type = 'category')
fig_preco_m2_cep.update_traces(textposition= 'outside')
fig_preco_m2_cep.show()

### 12. Análise de Correlação

In [78]:
#Correlação entre variaveis e preço

colunas_numericas = ['preco' , 'area_habitavel_m2' , 'quartos' , 'banheiros', 'andares', 'nota_design', 'area_porao_m2', 'area_habitavel_vizinhos_15_em_m2']

correlacao = (
    df_traduzido[colunas_numericas].corr()['preco'].sort_values(ascending=False).round(2)
)
print('Correlação com o preço é:')
print(correlacao)

Correlação com o preço é:
preco                               1.00
area_habitavel_m2                   0.70
nota_design                         0.67
area_habitavel_vizinhos_15_em_m2    0.59
banheiros                           0.53
area_porao_m2                       0.32
quartos                             0.32
andares                             0.26
Name: preco, dtype: float64

In [79]:
#Avaliando como a nota de design influencia no preço
fig_nota_design = px.scatter(
    df_traduzido,
    x='area_habitavel_m2',
    y='preco',
    color='nota_design',               # terceira dimensão: qualidade do imóvel
    color_continuous_scale='RdYlGn',   # vermelho (baixa nota) → verde (alta nota)
    opacity=0.5,
    title='Área vs Preço — colorido por Nota de Design',
    labels={
        'area_habitavel_m2': 'Área Habitável (m²)',
        'preco': 'Preço (USD)',
        'nota_design': 'Nota de Design'
    },
    hover_data=['quartos', 'vista_mar', 'cep']
)
fig_nota_design.show()