---
## 🔹 FASE 1 — Limpeza e Padronização

### 1. Consolidação e Tipagem

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv('Housing.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.0,2,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(15)
memory usage: 3.5 MB

In [6]:
cols = ['sqft_living','sqft_lot', 'sqft_above' ,'sqft_basement' , 'sqft_living15' , 'sqft_lot15']

for col in cols:
    df[col] = df[col] / 10.76389999

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  float64
 6   sqft_lot       21613 non-null  float64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  float64
 13  sqft_basement  21613 non-null  float64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  float64
 20  sqft_lot15     21613 non-null  float64
dtypes: datetime64[us](1), float64(11), int64(9)
memory usage: 3.5 MB

In [8]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [9]:
df['date'].unique()

<DatetimeArray>
['2014-10-13 00:00:00', '2014-12-09 00:00:00', '2015-02-25 00:00:00',
 '2015-02-18 00:00:00', '2014-05-12 00:00:00', '2014-06-27 00:00:00',
 '2015-01-15 00:00:00', '2015-04-15 00:00:00', '2015-03-12 00:00:00',
 '2015-04-03 00:00:00',
 ...
 '2015-03-08 00:00:00', '2014-08-30 00:00:00', '2015-05-27 00:00:00',
 '2015-03-22 00:00:00', '2015-02-15 00:00:00', '2014-10-11 00:00:00',
 '2015-02-01 00:00:00', '2014-11-30 00:00:00', '2014-08-24 00:00:00',
 '2014-07-27 00:00:00']
Length: 372, dtype: datetime64[us]

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,21613,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580306e+09,2014-10-29 04:38:01.959931,5.400886e+05,3.370795,2.114757,193.229196,1403.484572,1.494309,0.007542,0.234303,...,7.656873,166.147093,27.082103,1971.005136,84.402258,98077.939805,47.560053,-122.213896,184.556944,1186.229495
min,1.000102e+06,2014-05-02 00:00:00,7.500000e+04,0.000000,0.000000,26.941908,48.309628,1.000000,0.000000,0.000000,...,1.000000,26.941908,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,37.068349,60.479938
25%,2.123049e+09,2014-07-22 00:00:00,3.219500e+05,3.000000,1.750000,132.572766,468.231775,1.000000,0.000000,0.000000,...,7.000000,110.554725,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,138.425664,473.805963
50%,3.904930e+09,2014-10-16 00:00:00,4.500000e+05,3.000000,2.250000,177.444978,707.736044,1.500000,0.000000,0.000000,...,7.000000,144.928883,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,170.941759,707.921851
75%,7.308900e+09,2015-02-17 00:00:00,6.450000e+05,4.000000,2.500000,236.902981,992.948653,2.000000,0.000000,0.000000,...,8.000000,205.315917,52.025753,1997.000000,0.000000,98118.000000,47.678000,-122.125000,219.251387,936.742260
max,9.900000e+09,2015-05-27 00:00:00,7.700000e+06,33.000000,8.000000,1257.908380,153416.419842,3.500000,1.000000,4.000000,...,13.000000,874.218453,447.793087,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,576.928437,80937.206850
std,2.876570e+09,NaN,3.671268e+05,0.930105,0.770163,85.326034,3848.095166,0.539989,0.086517,0.766318,...,1.175459,76.932244,41.116607,29.373411,401.679240,53.505026,0.138564,0.140828,63.674997,2536.643750

In [12]:
#Convertendo para metros quadrados e traduzindo
mapeamento_colunas = {
    'id': 'id',
    'date': 'data',
    'price': 'preco',
    'bedrooms': 'quartos',
    'bathrooms': 'banheiros',
    'sqft_living': 'area_habitavel_m2',
    'sqft_lot': 'area_lote_m2',
    'floors': 'andares',
    'waterfront': 'vista_mar',
    'view': 'qualidade_vista',
    'condition': 'condicao_imovel',
    'grade': 'nota_design',
    'sqft_above': 'area_acima_solo_m2',
    'sqft_basement': 'area_porao_m2',
    'yr_built': 'ano_construcao',
    'yr_renovated': 'ano_reforma',
    'zipcode': 'cep',
    'lat': 'latitude',
    'long': 'longitude',
    'sqft_living15': 'area_habitavel_vizinhos_15_em_m2',
    'sqft_lot15': 'area_lote_vizinhos_15_em_m2'
}

# Aplicando a renomeação
df_traduzido= df.rename(columns=mapeamento_colunas)
# Verificando se deu certo
print("Colunas renomeadas com sucesso:")
print(df_traduzido.columns.tolist())

Colunas renomeadas com sucesso:
['id', 'data', 'preco', 'quartos', 'banheiros', 'area_habitavel_m2', 'area_lote_m2', 'andares', 'vista_mar', 'qualidade_vista', 'condicao_imovel', 'nota_design', 'area_acima_solo_m2', 'area_porao_m2', 'ano_construcao', 'ano_reforma', 'cep', 'latitude', 'longitude', 'area_habitavel_vizinhos_15_em_m2', 'area_lote_vizinhos_15_em_m2']

In [13]:
df_traduzido.head()

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,nota_design,area_acima_solo_m2,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2
0,7229300521,2014-10-13,231300.0,2,1.00,109.625693,524.902684,1.0,0,0,...,7,109.625693,0.000000,1955,0,98178,47.5112,-122.257,124.490194,524.902684
1,6414100192,2014-12-09,538000.0,3,2.25,238.761044,672.804467,2.0,0,0,...,7,201.599792,37.161252,1951,1991,98125,47.7210,-122.319,157.006290,709.687010
2,5631500400,2015-02-25,180000.0,2,1.00,71.535410,929.031300,1.0,0,0,...,6,71.535410,0.000000,1933,0,98028,47.7379,-122.233,252.696514,748.985034
3,2487200875,2014-12-09,604000.0,4,3.00,182.090135,464.515650,1.0,0,0,...,7,97.548286,84.541848,1965,0,98136,47.5208,-122.393,126.348257,464.515650
4,1954400510,2015-02-18,510000.0,3,2.00,156.077258,750.657290,1.0,0,0,...,8,156.077258,0.000000,1987,0,98074,47.6168,-122.045,167.225634,697.052184

In [14]:
df_traduzido[df_traduzido['quartos']>10]

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,nota_design,area_acima_solo_m2,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2
8757,1773100755,2014-08-21,520000.0,11,3.00,278.709390,460.799525,2.0,0,0,...,7,222.967512,55.741878,1918,1999,98106,47.5560,-122.363,131.922445,460.799525
15870,2402100895,2014-06-25,640000.0,33,1.75,150.503071,557.418780,1.0,0,0,...,7,96.619255,53.883815,1947,0,98103,47.6878,-122.331,123.561163,436.644711

In [15]:
df_traduzido= df_traduzido.drop(df_traduzido[df_traduzido['quartos']>30].index)

In [16]:
df_traduzido.describe()

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,nota_design,area_acima_solo_m2,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2
count,2.161200e+04,21612,2.161200e+04,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,...,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000,21612.000000
mean,4.580407e+09,2014-10-29 04:46:26.451971,5.400840e+05,3.369424,2.114774,193.231173,1403.523720,1.494332,0.007542,0.234314,...,7.656904,166.150310,27.080863,1971.006247,84.406163,98077.938645,47.560047,-122.213891,184.559767,1186.264179
min,1.000102e+06,2014-05-02 00:00:00,7.500000e+04,0.000000,0.000000,26.941908,48.309628,1.000000,0.000000,0.000000,...,1.000000,26.941908,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,37.068349,60.479938
25%,2.123049e+09,2014-07-22 00:00:00,3.218375e+05,3.000000,1.750000,132.526315,468.231775,1.000000,0.000000,0.000000,...,7.000000,110.554725,0.000000,1951.000000,0.000000,98033.000000,47.470975,-122.328000,138.425664,473.805963
50%,3.904930e+09,2014-10-16 00:00:00,4.500000e+05,3.000000,2.250000,177.444978,707.828947,1.500000,0.000000,0.000000,...,7.000000,144.928883,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,170.941759,707.921851
75%,7.308900e+09,2015-02-17 00:00:00,6.450000e+05,4.000000,2.500000,236.902981,992.971879,2.000000,0.000000,0.000000,...,8.000000,205.315917,52.025753,1997.000000,0.000000,98118.000000,47.678000,-122.125000,219.251387,936.765485
max,9.900000e+09,2015-05-27 00:00:00,7.700000e+06,11.000000,8.000000,1257.908380,153416.419842,3.500000,1.000000,4.000000,...,13.000000,874.218453,447.793087,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,576.928437,80937.206850
std,2.876598e+09,NaN,3.671347e+05,0.908026,0.770177,85.327513,3848.179892,0.539991,0.086519,0.766334,...,1.175477,76.932570,41.117154,29.373636,401.688123,53.505993,0.138564,0.140829,63.675119,2536.697313

In [17]:
df_traduzido.info()

<class 'pandas.DataFrame'>
Index: 21612 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                21612 non-null  int64
 1   data                              21612 non-null  datetime64[us]
 2   preco                             21612 non-null  float64
 3   quartos                           21612 non-null  int64
 4   banheiros                         21612 non-null  float64
 5   area_habitavel_m2                 21612 non-null  float64
 6   area_lote_m2                      21612 non-null  float64
 7   andares                           21612 non-null  float64
 8   vista_mar                         21612 non-null  int64
 9   qualidade_vista                   21612 non-null  int64
 10  condicao_imovel                   21612 non-null  int64
 11  nota_design                       21612 non-null  int64
 12  area_acima_solo_m2                21612 non-null  float64
 13  area_porao_m2                     21612 non-null  float64
 14  ano_construcao                    21612 non-null  int64
 15  ano_reforma                       21612 non-null  int64
 16  cep                               21612 non-null  int64
 17  latitude                          21612 non-null  float64
 18  longitude                         21612 non-null  float64
 19  area_habitavel_vizinhos_15_em_m2  21612 non-null  float64
 20  area_lote_vizinhos_15_em_m2       21612 non-null  float64
dtypes: datetime64[us](1), float64(11), int64(9)
memory usage: 3.6 MB

In [18]:
for col in ['vista_mar', 'qualidade_vista', 'condicao_imovel', 'nota_design', 'andares', 'quartos']:
    print(f'{col}: {sorted(df_traduzido[col].unique())}')

vista_mar: [np.int64(0), np.int64(1)]
qualidade_vista: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
condicao_imovel: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
nota_design: [np.int64(1), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
andares: [np.float64(1.0), np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0), np.float64(3.5)]
quartos: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11)]

---
## 🔹 FASE 2 — Consultas e Agregações

### 2. Análise Histórica de Preços

In [19]:
df_traduzido['ANO'] = df_traduzido['data'].dt.year
df_traduzido['MES'] = df_traduzido['data'].dt.month

In [20]:
df_traduzido.head()

,id,data,preco,quartos,banheiros,area_habitavel_m2,area_lote_m2,andares,vista_mar,qualidade_vista,...,area_porao_m2,ano_construcao,ano_reforma,cep,latitude,longitude,area_habitavel_vizinhos_15_em_m2,area_lote_vizinhos_15_em_m2,ANO,MES
0,7229300521,2014-10-13,231300.0,2,1.00,109.625693,524.902684,1.0,0,0,...,0.000000,1955,0,98178,47.5112,-122.257,124.490194,524.902684,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.761044,672.804467,2.0,0,0,...,37.161252,1951,1991,98125,47.7210,-122.319,157.006290,709.687010,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.535410,929.031300,1.0,0,0,...,0.000000,1933,0,98028,47.7379,-122.233,252.696514,748.985034,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.090135,464.515650,1.0,0,0,...,84.541848,1965,0,98136,47.5208,-122.393,126.348257,464.515650,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.077258,750.657290,1.0,0,0,...,0.000000,1987,0,98074,47.6168,-122.045,167.225634,697.052184,2015,2

In [ ]:
media_preco_ano = df_traduzido.groupby('ANO')['preco'].mean().round(2).reset_index().rename(columns={'preco' : 'Média de Preço'})
media_preco_ano

    ANO  Média de Preço
0  2014       539175.18
1  2015       541988.99

In [33]:
media_mensal_geral = df_traduzido.groupby(['ANO','MES'])['preco'].mean().reset_index().round(2)
media_mensal_geral

     ANO  MES      preco
0   2014    5  548080.28
1   2014    6  557964.57
2   2014    7  544788.76
3   2014    8  536445.28
4   2014    9  529253.82
5   2014   10  539031.98
6   2014   11  521961.01
7   2014   12  524461.87
8   2015    1  525870.89
9   2015    2  507851.37
10  2015    3  543977.19
11  2015    4  561837.77
12  2015    5  558126.81

In [34]:
#Gráfico de linha no periodo do datset 
media_mensal_geral['data_referencia'] = pd.to_datetime(media_mensal_geral['ANO'].astype(str)+ '-' +media_mensal_geral['MES'].astype(str) + '-01')

fig = px.line(media_mensal_geral , x ='data_referencia', y = 'preco', color='ANO', color_discrete_map={2014:'blue' , 2015:'red'} 
              , title = 'Comportamento de Preços: 2014 (Azul) vs 2015 (Vermelho)', markers =True)

fig.update_xaxes(
    dtick = 'M1',
    tickformat='%b\n%Y',
    ticklabelmode="period"

)
fig.show()

In [47]:
cep_diferentes=df_traduzido['cep'].unique()
cep_diferentes

array([98178, 98125, 98028, 98136, 98074, 98053, 98003, 98198, 98146,
       98038, 98007, 98115, 98107, 98126, 98019, 98103, 98002, 98133,
       98040, 98092, 98030, 98119, 98112, 98052, 98027, 98117, 98058,
       98001, 98056, 98166, 98023, 98070, 98148, 98105, 98042, 98008,
       98059, 98122, 98144, 98004, 98005, 98034, 98075, 98116, 98010,
       98118, 98199, 98032, 98045, 98102, 98077, 98108, 98168, 98177,
       98065, 98029, 98006, 98109, 98022, 98033, 98155, 98024, 98011,
       98031, 98106, 98072, 98188, 98014, 98055, 98039])

In [49]:
contagem_ceps= df_traduzido['cep'].value_counts().reset_index()

contagem_ceps.collumns = ['CEP', 'Frequêcia']

contagem_ceps

/tmp/ipykernel_21786/4094461203.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  contagem_ceps.collumns = ['CEP', 'Frequêcia']

      cep  count
0   98103    601
1   98038    590
2   98115    583
3   98052    574
4   98117    553
..    ...    ...
65  98102    105
66  98010    100
67  98024     81
68  98148     57
69  98039     50

[70 rows x 2 columns]